import Head from 'next/head' 
import styles from '../styles/Home.module.css'
import { GraphQLClient,gql } from 'graphql-request';
import {BlogCard} from "../components/BlogCard";

const graphcms = new GraphQLClient("https://api-eu-west-2.graphcms.com/v2/cl21zpqgk4oep01xtflkm1vff/master");

const QUERY = gql`
{
  posts{
    id,
    title,
    datePublished,
    slug,
    content{
      html
    }
    author{
      name,
      avatar{
        url
      }
    }
    coverPhoto{
      url
    }
  }
}
`;

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return{
    props:{
      posts,
    },
    revalidate:10,
  };
}

export default function Home({posts}: {posts:any}) {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post:any)=>(
          <BlogCard title={post.title} author = {post.author} coverPhoto = {post.node.coverPhoto} key = {post.id} datePublished = {post.datePublished} slug={post.slug} />
        ))}
      </main>

      
    </div>
  )
}
